name/urls.py
from django.urls import path, re_path
from django.contrib import admin

from . import views, feeds
from .api import views as api


admin.autodiscover()

app_name = 'name'
urlpatterns = [
    path('', views.landing, name='landing'),
    path('about/', views.about, name='about'),
    path('export/', views.export, name='export'),
    path('export.json', views.export_json, name='export_json'),
    path('feed/', feeds.NameAtomFeed(), name='feed'),
    re_path(r'label/(?P<name_value>.*)$', views.label, name='label'),
    path('locations.json', api.locations_json, name='locations-json'),
    path('map/', views.locations, name='map'),
    path('opensearch.xml', views.opensearch, name='opensearch'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('search.json', api.search_json, name="search-json"),
    path('stats.json', api.stats_json, name='stats-json'),
    path('stats/', views.stats, name='stats'),
    path('<slug:name_id>.json', api.name_json, name='detail-json'),
    path('<slug:name_id>.mads.xml', views.mads_serialize, name='mads-serialize'),
    path('<name_id>/', views.detail, name='detail')
]

name/models.py
import json
from datetime import datetime
from itertools import groupby
from urllib.parse import quote
from urllib.request import urlopen

import markdown2
from django.urls import reverse
from django.db import models, transaction
from django.utils import timezone
from pynaco.naco import normalizeSimplified

from .validators import validate_merged_with


class Identifier_Type(models.Model):
    """Custom Identifier Type.

    Used in conjunction with the Identifier model.
    """
    label = models.CharField(
        max_length=255,
        help_text='What kind of data is this? Personal website? Twitter?')

    icon_path = models.CharField(
        max_length=255,
        blank=True,
        help_text='Path to icon image?')

    homepage = models.URLField(
        blank=True,
        help_text='Homepage of label. Twitter.com, Facebook.com, etc')

    class Meta:
        ordering = ['label']
        verbose_name = 'Identifier Type'

    def __str__(self):
        return self.label


class Identifier(models.Model):
    """An Identifier for a Name models instance. Most commonly
    represented as a permalink.

    This is used in conjunction with the Identifier Type model to
    specify the type of Identifier the instance represents. An example
    instance would have an Identifier Type of `Twitter` and the value
    field would have the permalink to the Name's Twitter profile page.
    """
    type = models.ForeignKey(
        'Identifier_Type',
        help_text="Catagorize this record's identifiers here",
        on_delete=models.CASCADE)

    belong_to_name = models.ForeignKey('Name', on_delete=models.CASCADE)
    value = models.CharField(max_length=500)
    visible = models.BooleanField(default=True)
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ['order', 'type']

    def __str__(self):
        return self.value


class NoteManager(models.Manager):
    """Custom Model Manager for the Note model."""
    def public_notes(self):
        return self.get_queryset().exclude(note_type=self.model.NONPUBLIC)


class Note(models.Model):
    """A note regarding the related Name model instance."""
    BIOGRAPHICAL_HISTORICAL = 0
    DELETION_INFORMATION = 1
    NONPUBLIC = 2
    SOURCE = 3
    OTHER = 4

    NOTE_TYPE_CHOICES = (
        (BIOGRAPHICAL_HISTORICAL, 'Biographical/Historical'),
        (DELETION_INFORMATION, 'Deletion Information'),
        (NONPUBLIC, 'Nonpublic'),
        (SOURCE, 'Source'),
        (OTHER, 'Other')
    )

    note = models.TextField(help_text='Enter notes about this record here')
    note_type = models.IntegerField(choices=NOTE_TYPE_CHOICES)
    belong_to_name = models.ForeignKey('Name', on_delete=models.CASCADE)

    objects = NoteManager()

    class Meta:
        base_manager_name = 'objects'

    def get_note_type_label(self):
        """Returns the label associated with an instance's
        note_type.
        """
        id, note_type = self.NOTE_TYPE_CHOICES[self.note_type]
        return note_type

    def __str__(self):
        return self.note


class Variant(models.Model):
    """Defines an alternative form that a Name may be displayed."""
    ACRONYM = 0
    ABBREVIATION = 1
    TRANSLATION = 2
    EXPANSION = 3
    OTHER = 4

    VARIANT_TYPE_CHOICES = (
        (ACRONYM, 'Acronym'),
        (ABBREVIATION, 'Abbreviation'),
        (TRANSLATION, 'Translation'),
        (EXPANSION, 'Expansion'),
        (OTHER, 'Other')
    )

    belong_to_name = models.ForeignKey('Name', on_delete=models.CASCADE)
    variant_type = models.IntegerField(
        choices=VARIANT_TYPE_CHOICES,
        help_text='Choose variant type.')

    variant = models.CharField(
        max_length=255,
        help_text='Fill in the other name variants, if any.')

    normalized_variant = models.CharField(
        max_length=255,
        editable=False,
        help_text='NACO normalized variant text')

    def get_variant_type_label(self):
        """Returns the label associated with an instance's
        variant_type.
        """
        id, variant_type = self.VARIANT_TYPE_CHOICES[self.variant_type]
        return variant_type

    def save(self, *args, **kwargs):
        self.normalized_variant = normalizeSimplified(self.variant)
        if 'update_fields' in kwargs:
            kwargs['update_fields'] = {'normalized_variant'}.union(kwargs['update_fields'])
        super(Variant, self).save(*args, **kwargs)

    def __str__(self):
        return self.variant


class TicketingManager(models.Manager):
    """Custom manager for the BaseTicketing model."""

    def create(self, *args, **kwargs):
        """Override the create method.

        Create or get the single object. If one already exists,
        delete it and create a new one so we auto-increment the id.
        """
        obj, created = self.get_or_create(stub=self.model.STUB_DEFAULT)
        if not created:
            with transaction.atomic():
                obj.delete()
                obj = self.create(stub=self.model.STUB_DEFAULT)
        return obj


class BaseTicketing(models.Model):
    """Creates a custom app-level identifier.

    This leverages the autoincrement primary key field to
    create custom unique identifier. An example identifier
    would be `nm0000001`.
    """
    # Explicitly set the id of the model, even though it is the same
    # as the one Django gives it.
    id = models.AutoField(null=False, primary_key=True)

    # This is just the smallest placeholder we can create that we can
    # replace into to generate a new id.
    STUB_DEFAULT = True
    stub = models.BooleanField(null=False, default=STUB_DEFAULT, unique=True)

    # Override the default manager
    objects = TicketingManager()

    @property
    def ticket(self):
        """Alias for id"""
        return self.id

    def __str__(self):
        return 'nm{ticket:07d}'.format(ticket=self.ticket)


class NameManager(models.Manager):
    """Custom Manager for the Name model.

    Provides additional methods that are useful in calculating
    statistics on Name model instances.
    """

    def visible(self):
        """Retrieves all Name objects that have an Active record status
        and are not merged with any other Name objects.
        """
        return self.get_queryset().filter(
            record_status=self.model.ACTIVE, merged_with=None)

    def active_type_counts(self):
        """Calculates counts of Name objects by Name Type.

        Statistics are based off of the queryset returned by visible.
        The total number is calculated using the count method. All
        additional figures are calculated using Python to reduce the number
        of queries.
        """
        names = self.visible()
        return {
            'total': names.count(),
            'personal': len([n for n in names if n.is_personal()]),
            'organization': len([n for n in names if n.is_organization()]),
            'event': len([n for n in names if n.is_event()]),
            'software': len([n for n in names if n.is_software()]),
            'building': len([n for n in names if n.is_building()])
        }

    def _counts_per_month(self, date_column):
        """Calculates the number of Names by month according to the
        date_column passed in.

        This will return a ValueQuerySet where each element is in the form
        of
            {
               count: <Number of Names for the month>,
               month: <Datetime object for first day of the given month>
            }
        """
        def grouper(name):
            return (getattr(name, date_column).year,
                    getattr(name, date_column).month)

        def convert_key(year, month):
            datetime_obj = datetime(year=year, month=month, day=1)
            tzinfo = timezone.get_current_timezone()
            return timezone.make_aware(datetime_obj, tzinfo)

        results = self.all().order_by(date_column)

        return [
            dict(month=convert_key(*key), count=len(list(value)))
            for key, value in groupby(results, grouper)
        ]

    def created_stats(self):
        """Returns a list of the number of Names created per
        month.
        """
        return self._counts_per_month('date_created')

    def modified_stats(self):
        """Returns a list of the number of Names modified per
        month.
        """
        return self._counts_per_month('last_modified')


class Name(models.Model):
    """The authorized version of a name that is used to unambiguously
    refer to a person, organization, event, building or piece of
    software.
    """
    ACTIVE = 0
    DELETED = 1
    SUPPRESSED = 2

    RECORD_STATUS_CHOICES = (
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted'),
        (SUPPRESSED, 'Suppressed')
    )

    PERSONAL = 0
    ORGANIZATION = 1
    EVENT = 2
    SOFTWARE = 3
    BUILDING = 4

    NAME_TYPE_CHOICES = (
        (PERSONAL, 'Personal'),
        (ORGANIZATION, 'Organization'),
        (EVENT, 'Event'),
        (SOFTWARE, 'Software'),
        (BUILDING, 'Building')
    )

    DATE_DISPLAY_LABELS = {
        PERSONAL: {
            'type': 'Personal',
            'begin': 'Date of Birth',
            'end': 'Date of Death'
        },
        ORGANIZATION: {
            'type': 'Organization',
            'begin': 'Founded Date',
            'end': 'Defunct'
        },
        EVENT: {
            'type': 'Event',
            'begin': 'Begin Date',
            'end': 'End Date'
        },
        SOFTWARE: {
            'type': 'Software',
            'begin': 'Begin Date',
            'end': 'End Date'
        },
        BUILDING: {
            'type': 'Building',
            'begin': 'Erected Date',
            'end': 'Demolished Date',
        },
        None: {
            'type': None,
            'begin': 'Born/Founded Date',
            'end': 'Died/Defunct Date'
        }
    }

    NAME_TYPE_SCHEMAS = {
        PERSONAL: 'http://schema.org/Person',

name/views.py
import csv

from django import http
from django.views import generic
from django.urls import reverse
from django.templatetags.static import static
from django.shortcuts import get_object_or_404, render, redirect
from pynaco.naco import normalizeSimplified

from .models import Name, Identifier
from .utils import filter_names


def label(request, name_value):
    """Find a name by label.

    If the label matches a single name, users are redirected
    to the name detail page. Otherwise, if the label
    does not exist, or the specified label matches multiple Name
    objects, a status code 404 is returned.
    """
    if not name_value:
        return http.HttpResponseNotFound()

    normalized_name = normalizeSimplified(name_value)
    try:
        name = Name.objects.get(normalized_name=normalized_name)

        return http.HttpResponseRedirect(
            reverse('name:detail', args=[name.name_id]))

    except Name.DoesNotExist:
        return http.HttpResponseNotFound(
            'No matching term found - authoritative or variant - for "{0}"'
            .format(name_value))

    except Name.MultipleObjectsReturned:
        return http.HttpResponseNotFound(
            'There are multiple Name objects with the same name: "{0}".'
            .format(normalized_name))


def detail(request, name_id):
    """View for the Name detail page."""
    queryset = (
        Name.objects.select_related().
        prefetch_related('identifier_set__type')
    )

    name_entry = get_object_or_404(queryset, name_id=name_id)

    if name_entry.merged_with:
        return redirect(name_entry.merged_with)

    elif name_entry.is_suppressed():
        return http.HttpResponseNotFound(
            'The requested record could not be found.')

    elif name_entry.is_deleted():
        return http.HttpResponseGone('The requested record has been deleted!')

    return render(request, 'name/name_detail.html', dict(name=name_entry))


def export(request):
    """Exports Names to a TSV file."""
    # Create a CSV response.
    response = http.HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="data.tsv"'

    writer = csv.writer(response, delimiter='\t', quoting=csv.QUOTE_MINIMAL)

    # Iterate through the visible Names that are not merged with any other
    # Name records and write a row for each record.
    for n in Name.objects.visible():
        writer.writerow([
            n.get_name_type_label().lower(),
            n.name,
            request.build_absolute_uri(n.get_absolute_url())
        ])

    return response


def export_json(request):
    """Exports visible Names to a JSON list."""
    names = []
    for n in Name.objects.visible():
        names.append({
            'i': n.name_id,
            'l': request.build_absolute_uri(n.get_absolute_url()),
            't': n.name,
        })

    return http.JsonResponse(data=names, safe=False)


def opensearch(request):
    """Renders an Opensearch XML file.

    Opensearch URL templates are composed in the view
    to more easily compose the absolute url with the
    query string.
    """
    # Query templates for the URLs.
    search_query = '{0}?q_type=Personal&q={{searchTerms}}'
    search_json_query = '{0}?q={{searchTerms}}'

    # Build the absolute URLs.
    search_url = request.build_absolute_uri(reverse('name:search'))
    search_json_url = request.build_absolute_uri(reverse('name:search-json'))

    # Compose the full URLs that will be sent to the template.
    search = search_query.format(search_url)
    search_json = search_json_query.format(search_json_url)
    image = request.build_absolute_uri(static('name/img/favicon.png'))

    urls = dict(search=search, search_json=search_json, image=image)

    return render(request, 'name/opensearch.xml',
                  urls, content_type='text/xml')


def about(request):
    """View for the About page."""
    return render(request, 'name/about.html')


def stats(request):
    """View for the Stats page."""
    context = dict(
        total_names=Name.objects.visible().count(),
        total_identifiers=Identifier.objects.count()
    )
    return render(request, 'name/stats.html', context)


def landing(request):
    """View for the Landing page."""
    counts = dict(counts=Name.objects.active_type_counts())
    return render(request, 'name/landing.html', counts)


def locations(request):
    """View for the Map page."""
    return render(request, 'name/map.html')


class SearchView(generic.ListView):
    model = Name
    template_name = 'name/search.html'
    paginate_by = 15

    VALID_SORTS = {
        'name_a': 'name',
        'name_d': '-name',
        'begin_a': 'begin',
        'begin_d': '-begin',
        'end_a': 'end',
        'end_d': '-end',
    }

    DEFAULT_SORT = VALID_SORTS['name_a']

    def get_sort_method(self):
        order = self.request.GET.get('order', '')
        return self.VALID_SORTS.get(order, self.DEFAULT_SORT)

    def get_queryset(self):
        query = self.request.GET
        if query.get('q') or query.get('q_type'):
            return filter_names(self.request).order_by(self.get_sort_method())
        return Name.objects.none()


def mads_serialize(request, name_id):
    """Renders the Name serialized into the MADS XML format."""
    queryset = (
        Name.objects.select_related()
        .prefetch_related('identifier_set__type', 'note_set', 'variant_set')
    )

    context = dict(name=get_object_or_404(queryset, name_id=name_id))

    return render(request, 'name/name.mads.xml',
                  context, content_type='text/xml')

name/templates/name/_navbar.html
<div class="navbar navbar-default navbar-fixed navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url "name:landing" %}">{{ name_app_title }}</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url "name:stats" %}">Statistics</a></li>
                        <li><a href="{% url "name:map" %}">Map</a></li>
                    </ul>
                </li>
                <li><a href="{% url "name:about" %}">About</a></li>
                <li><a href="{% url "name:feed" %}"><span class="fa fa-rss"></span></a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right hidden-md hidden-lg">
                <li><a href="{% url "name:search" %}"><span class="fa fa-search"></span></a></li>
            </ul>
            <form class="navbar-form navbar-right hidden-xs hidden-sm" id="search" action="{% url "name:search" %}">
                <div class="form-group">
                    <select class="form-control" name="q_type" id="q_type">
                        {# Show current searched type as the default selection, if it exists #}
                        {% for k, v in name_types.items %}
                            {% if request.GET.q_type == v %}
                                <option value="{{ v }}" selected>{{ v }}</option>
                            {% else %}
                                <option value="{{ v }}">{{ v }}</option>
                            {% endif %}
                        {% endfor %}
                        <option value="Any Type" {% if not request.GET.q_type or request.GET.q_type == "Any Type" %}selected{% endif %}>Any Type</option>
                    </select>
                    <input class="form-control" type="text" name="q" id="names" value="{{ q }}">
                    <input type="hidden" value="{% url "name:search-json" %}" id="autocomplete">
                    <button class="btn btn-default" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

name/templates/name/base.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "https://www.w3.org/TR/html4/strict.dtd">

<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="search" type="application/opensearchdescription+xml" title="{{ name_app_title }} Search" href="{% url "name:opensearch" %}">
    <link rel="icon" type="image/png" href="{% static "name/img/favicon.png" %}">

    <link rel="stylesheet" href="{% static 'name/css/name.css' %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.4/paper/bootstrap.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" type="text/css" media="all">

    <script type="text/javascript" src="//code.jquery.com/jquery-latest.js"></script>
    <script src="//code.jquery.com/ui/1.9.2/jquery-ui.js" type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="{% static "name/js/ajax-form.js" %}"></script>

    {%  block head-extra %}{% endblock %}
</head>
<body>
    {% include "name/_navbar.html" %}
    <div id="body">
        {% block body %}
            <div class="content_title">
                {% block content_title %}{% endblock content_title %}
            </div>

            <div class="container">
                {% block content %}{% endblock content %}
            </div>
        {% endblock body %}
    </div>
</body>
</html>

name/templates/name/map.html
{% extends "name/base.html" %}
{% load static %}

{% block head-extra %}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/leaflet/0.6.4/leaflet.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/leaflet/0.6.4/leaflet.js"></script>

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.Default.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/leaflet.markercluster.js"></script>
{% endblock %}

{% block title %}Map{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <form name="map" action="{% url "name:locations-json" %}">
                <span id="attribution" class="hidden">&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap</a> contributors</span>
            </form>
            <div id="map" style="width: 100%; height: 800px"></div>
        </div>
    </div>

    <script src="{% static "name/js/map.js" %}"></script>
{% endblock %}

name/templates/name/name_detail.html
{% extends "name/base.html" %}
{% load static %}
{% load name_extras %}

{% block title %}{{ name.name }}{% endblock %}

{% block head-extra %}
    <link rel="canonical" href="{% absolute_url "name:detail" name %}">
    <link rel="alternate" type="application/xml" href="{% url "name:mads-serialize" name %}">
    <link rel="alternate" type="application/json" href="{% url "name:detail-json" name %}">
{% endblock head-extra %}

{% block content %}

    <div {% if name.has_schema_url %}itemscope itemtype="{{ name.get_schema_url }}{% endif %}">
        {% with name.location_set.current_location as current_location %}
            {% if name.is_building and current_location %}
                <div itemprop="geo" itemscope itemtype="https://schema.org/GeoCoordinates">
                    <meta itemprop="latitude" content="{{ current_location.latitude }}" />
                    <meta itemprop="longitude" content="{{ current_location.longitude }}" />
                </div>
            {% endif %}
        {% endwith %}

        <h2 class="named">{{ name.name }}</h2>

        {% if user.is_authenticated %}
            <div class="control-btns">
                <a class="btn btn-default" href="{% url "admin:name_name_change" name.id %}">Edit</a>
            </div>
        {% endif %}

        <table class="table table-striped">
            <colgroup><col class="labels"><col class="data"></colgroup>
            <tr>
                <th>Authorized:</th>
                <td >
                    <!-- all schema "Things" have a name property -->
                    <span itemprop="name">{{ name.name }}</span>
                </td>
            </tr>
            <tr>
                <th>Name Type:</th>
                <td>{{ name.get_name_type_label }}</td>
            </tr>

            {# Locations #}
            {% if name.is_building %}
                {% for l in name.location_set.all %}
                    <tr>
                        <th>Location: <em><small>({% if l.is_current %}current{% else %}former{% endif %})</small></em></th>
                        <td>{{ l.latitude }}, {{ l.longitude }}</td>
                    </tr>
                {% endfor %}
            {% endif %}

            <tr>
                <th>URI:</th>
                <td>
                    <a href='{{ request.build_absolute_uri }}'><span itemprop='url'>{{ request.build_absolute_uri }}</span></a>
                </td>
            </tr>

            {% if name.disambiguation %}
                <tr>
                   <th>Disambiguation:</th>
                   <td>
                        {{ name.disambiguation }}
                    </td>
                </tr>
            {% endif %}

            {# FIXME: There is a lot of nesting here #}

            {% if name.begin %}
                <tr>
                    <th>{{ name.get_date_display.begin }}: </th>
                    <td>
                        {% if name.is_personal %}
                            <span itemprop="birthDate">{{ name.begin }}</span>
                        {% elif name.is_organization %}
                                <span itemprop="foundingDate">{{ name.begin }}</span>
                        {% elif name.is_building %}
                            <span itemprop="additionalProperty" itemscope itemtype="https://schema.org/PropertyValue">
                                <meta itemprop="name" content="erectedDate">
                                <span itemprop="value">{{ name.begin }}</span>
                            </span>
                        {% elif name.is_event %}
                            <span itemprop="startDate">{{ name.begin }}</span>
                        {% else %}
                            {{ name.begin }}
                        {% endif %}
                    </td>
                </tr>
            {% endif %}

            {% if name.end %}
                <tr>
                    <th>{{ name.get_date_display.end }}: </th>
                    <td>
                        {% if name.is_personal %}
                            <span itemprop="deathDate">{{ name.end }}</span>
                        {% else %}
                            {{ name.end }}
                        {% endif %}
                    </td>
                </tr>
            {% endif %}

            <!-- BIOGRAPHY -->
            {% if name.biography %}
                <tr>
                    <th>
                        {% if name.is_personal %}
                            Biographical Info:
                        {% else %}
                            History:
                        {% endif %}
                    </th>
                    <td>
                        {{ name.render_biography|safe }}
                    </td>
                </tr>
            {% endif %}

            <!-- LINKS -->
            <tr>
                <th>Links:</th>
                <td>
                    <ul class="list-unstyled">
                        {% if name.identifier_set.exists %}
                            {% for link in name.identifier_set.all %}
                                {% if name.is_active and link.visible %}
                                    <li>
                                        {% if link.type.icon_path %}
                                            <img alt="icon" src="{% static link.type.icon_path %}" style="max-width: 16px">
                                        {% else %}
                                            <span class="fa fa-leaf"></span>
                                        {% endif %}

                                        {% if "http" in link|escape or ".edu" in link|escape or ".com" in link|escape %}
                                            <strong>{{ link.type }}:</strong> <a itemprop="sameAs" href="{{ link }}">{{ link }}</a>
                                        {% else %}
                                            {% if "@" in link|escape %}
                                                {{ link.type }}:
                                                <a href="{{ link }}"><span itemprop="email">{{ link }}</span></a>
                                            {% else %}
                                                <strong>{{ link.type }}:</strong> {{ link }}
                                            {% endif %}
                                        {% endif %}
                                    </li>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </ul>
                </td>
            </tr>

            <!-- VARIANTS -->
            {% if name.variant_set.all %}
                <tr>
                    {% if name.is_organization %}
                        <th>Variant Name:</th>
                    {% elif name.is_building %}
                        <th>Also Known As:</th>
                    {% else %}
                        <th>Publishes As:</th>
                    {% endif %}

                    <td>
                        <ul class="list-unstyled">
                            {% for variant in name.variant_set.all %}
                                <li>
                                    {% if name.is_personal %}
                                        <span itemprop="additionalName">{{ variant }}</span>
                                    {% else %}
                                        <span itemprop="alternateName">{{ variant }}</span>
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            {% endif %}

            <!-- NOTES -->
            {% with name.note_set.public_notes as public_notes %}
                {% if public_notes %}
                    <tr>
                        <th>Notes:</th>
                        <td>{{ public_notes|join:"<br>" }}</td>
                    </tr>
                {% endif %}
            {% endwith %}
        </table>

        {# This will only display if the Name is a Building #}
        {% if name.is_building and name.has_current_location %}
            {% with name.location_set.current_location as current_location %}
                <a itemprop="map" href="https://maps.google.com/maps?q={{ current_location.latitude }},{{ current_location.longitude }}&hl=en&sll={{ current_location.latitude }},{{ current_location.longitude }}&sspn=0.498085,0.521851&t=m&z=17"><img alt='Building Location' src="https://maps.googleapis.com/maps/api/staticmap?center={{ current_location.latitude }},{{ current_location.longitude }}&zoom=15&size=300x300&sensor=false&markers=color:blue%7Clabel:{{name}}%7C{{ current_location.latitude }},{{ current_location.longitude }}" class='img-circle img-polaroid pull-right' ></a>
            {% endwith %}
        {% endif %}

        <h3>Alternate Formats</h3>
        <div>
            <a class="btn btn-default" href="{% url "name:mads-serialize" name.name_id %}">MADS/XML</a>
            <a class="btn btn-default" href="{% url "name:detail-json" name.name_id %}">JSON</a>
        </div>
    </div>
{% endblock content %}